// apps/create-react-app/src/mitosis/components/PlaylistDetails.tsx
import TrackIcon from "./TrackIcon";

type PlaylistDetailsProps = {
  name: string;
  description: string | null;
  tracksTotal: number;
};

function PlaylistDetails(props: PlaylistDetailsProps) {
  return (
    <div className="grid grid-rows-2">
      <div>
        <h2 className="text-2xl font-medium">{props.name}</h2>

        <p className="font-light">{props.description}</p>
      </div>

      <div className="flex gap-3 font-light self-center mb-2">
        <TrackIcon />

        {props.tracksTotal}
      </div>
    </div>
  );
}

export default PlaylistDetails;

// apps/svelte-kit-app/src/mitosis/components/PlaylistDetails.svelte
<script context="module" lang="ts">
	type PlaylistDetailsProps = {
		name: string;
		description: string | null;
		tracksTotal: number;
	};
</script>

<script lang="ts">
	import TrackIcon from './TrackIcon.svelte';

	export let name: PlaylistDetailsProps['name'];
	export let description: PlaylistDetailsProps['description'];
	export let tracksTotal: PlaylistDetailsProps['tracksTotal'];
</script>

<div class="grid grid-rows-2">
	<div>
		<h2 class="text-2xl font-medium">{name}</h2>
		<p class="font-light">{description}</p>
	</div>
	<div class="flex gap-3 font-light self-center mb-2">
		<TrackIcon />
		{tracksTotal}
	</div>
</div>
