// apps/nextjs-app/mitosis/components/TableHeader.tsx
import * as React from "react";

type TableHeaderProps = {
  children: any;
  sorted: boolean;
  ascending: boolean;
};
import DownArrow from "./DownArrow";
import UpArrow from "./UpArrow";

function TableHeader(props: TableHeaderProps) {
  return (
    <div className="flex items-center gap-4 w-full">
      <div>{props.children}</div>

      {props.sorted ? (
        <>
          {props.ascending ? (
            <>
              <div>
                <UpArrow />
              </div>
            </>
          ) : (
            <div>
              <DownArrow />
            </div>
          )}
        </>
      ) : (
        <div className="w-6"> </div>
      )}
    </div>
  );
}

export default TableHeader;

// apps/svelte-kit-app/src/mitosis/components/TableHeader.svelte
<script context="module" lang="ts">
  type TableHeaderProps = {
    children: any;
    sorted: boolean;
    ascending: boolean;
  };
</script>

<script lang="ts">
  import DownArrow from "./DownArrow.svelte";
  import UpArrow from "./UpArrow.svelte";

  export let sorted: TableHeaderProps["sorted"];
  export let ascending: TableHeaderProps["ascending"];
</script>

<div class="flex items-center gap-4 w-full">
  <div><slot /></div>

  {#if sorted}
    {#if ascending}
      <div>
        <UpArrow />
      </div>
    {:else}
      <div>
        <DownArrow />
      </div>
    {/if}
  {:else}
    <div class="w-6" />
  {/if}
</div>
