// packages/framework-compare-mitosis/svelte/components/TrackTable.svelte
<script context="module" lang="ts">
  type TrackTableProps = {
    children: any;
    titleSlot: any;
    artistSlot: any;
    durationSlot: any;
  };
</script>

<script lang="ts">
  export let titleSlot: TrackTableProps["titleSlot"];
  export let artistSlot: TrackTableProps["artistSlot"];
  export let durationSlot: TrackTableProps["durationSlot"];
</script>

<div class="border border-[#f4f4f444] rounded-lg">
  <table class="table-auto w-full">
    <thead>
      <tr>
        <th class="absolute max-w-0 overflow-hidden left-[-99999px]"
          >Album Image</th
        >
        <th class="text-xl font-normal py-2 px-2 text-start">{titleSlot}</th>

        <th class="text-xl font-normal py-2 px-2 text-start">{artistSlot}</th>
        <th class="text-xl font-normal py-2 px-2 pr-6">{durationSlot}</th>
      </tr>
    </thead>
    <tbody><slot /></tbody>
  </table>
</div>

// packages/framework-compare-mitosis/react/components/TrackTable.tsx
import * as React from "react";

type TrackTableProps = {
  children: any;
  titleSlot: any;
  artistSlot: any;
  durationSlot: any;
};

function TrackTable(props: TrackTableProps) {
  return (
    <div className="border border-[#f4f4f444] rounded-lg">
      <table className="table-auto w-full">
        <thead>
          <tr>
            <th className="absolute max-w-0 overflow-hidden left-[-99999px]">
              Album Image
            </th>

            <th className="text-xl font-normal py-2 px-2 text-start">
              {props.titleSlot}
            </th>

            <th className="text-xl font-normal py-2 px-2 text-start">
              {props.artistSlot}
            </th>

            <th className="text-xl font-normal py-2 px-2 pr-6">
              {props.durationSlot}
            </th>
          </tr>
        </thead>

        <tbody>{props.children}</tbody>
      </table>
    </div>
  );
}

export default TrackTable;
