// packages/framework-compare-mitosis/svelte/components/TableHeaderButton.svelte
<script context="module" lang="ts">
  type TableHeaderButtonProps = {
    children: any;
    sorted: boolean;
    ascending: boolean;
  } & HTMLButtonElement;
</script>

<script lang="ts">
  import { ASCENDING, SortDirection } from "framework-compare-types";
  import DownArrow from "./DownArrow.svelte";
  import UpArrow from "./UpArrow.svelte";

  export let sorted: TableHeaderButtonProps["sorted"];
  export let ascending: TableHeaderButtonProps["ascending"];
</script>

<button {...$$props}>
  <slot />

  {#if sorted}
    <div>
      {#if ascending}
        <UpArrow />
      {:else}
        <DownArrow />
      {/if}
    </div>
  {/if}
</button>

// packages/framework-compare-mitosis/vue/vue3/components/TableHeaderButton.vue
<template>
  <button v-bind="$props">
    <slot />

    <template v-if="sorted">
      <div>
        <template v-if="ascending">
          <up-arrow></up-arrow>
        </template>

        <template v-else>
          <down-arrow></down-arrow>
        </template>
      </div>
    </template>
  </button>
</template>

<script lang="ts">
type TableHeaderButtonProps = {
  children: any;
  sorted: boolean;
  ascending: boolean;
} & HTMLButtonElement;

import { ASCENDING, SortDirection } from "framework-compare-types";
import DownArrow from "./DownArrow.vue";
import UpArrow from "./UpArrow.vue";

export default {
  name: "table-header-button",
  components: { DownArrow: DownArrow, UpArrow: UpArrow },
  props: ["sorted", "ascending"],
};
</script>
