// apps/create-react-app/src/mitosis/components/UpArrow.tsx
import * as React from "react";

function UpArrow(props: any) {
  return (
    <svg viewBox="0 0 24 24" className="w-6">
      <g>
        <path fill="none" d="M0 0h24v24H0z" />

        <path
          d="M13 7.828V20h-2V7.828l-5.364 5.364-1.414-1.414L12 4l7.778 7.778-1.414 1.414L13 7.828z"
          className="fill-white"
        />
      </g>
    </svg>
  );
}

export default UpArrow;

// packages/framework-compare-mitosis/vue/vue3/components/UpArrow.vue
<template>
  <svg viewBox="0 0 24 24" class="w-6">
    <g>
      <path fill="none" d="M0 0h24v24H0z"></path>
      <path
        d="M13 7.828V20h-2V7.828l-5.364 5.364-1.414-1.414L12 4l7.778 7.778-1.414 1.414L13 7.828z"
        class="fill-white"
      ></path>
    </g>
  </svg>
</template>

<script lang="ts">
export default {
  name: "up-arrow",
};
</script>
