// apps/create-react-app/src/routes/playlist.tsx
import { GetPlaylistsResponse } from "framework-compare-api";
import {
  PlaylistImage,
  PlaylistList,
  PlaylistListItem,
  PlaylistDetails,
  PlaylistLink,
} from "framework-compare-mitosis/dist/react";
import { useLoaderData } from "react-router-dom";

export const Playlist = () => {
  const response = useLoaderData() as GetPlaylistsResponse;

  return (
    <PlaylistList>
      {response.items.map((p) => (
        <PlaylistListItem key={p.id}>
          <PlaylistLink href={`/playlist/${p.id}`}>
            <PlaylistImage name={p.name} url={p.images[0].url} />
            <PlaylistDetails
              name={p.name}
              description={p.description}
              tracksTotal={p.tracks.total}
            />
          </PlaylistLink>
        </PlaylistListItem>
      ))}
    </PlaylistList>
  );
};

// apps/svelte-kit-app/src/routes/playlist/+page.svelte
<script>
	import {
		PlaylistList,
		PlaylistListItem,
		PlaylistLink,
		PlaylistImage,
		PlaylistDetails
	} from '../../mitosis';

	/** @type {import('./$types').PageData} */
	export let data;
</script>

<PlaylistList>
	{#each data.items as playlist}
		<PlaylistListItem v-for="playlist in playlists">
			<PlaylistLink href={`/playlist/${playlist.id}`}>
				<PlaylistImage name={playlist.name} url={playlist.images[0].url} />
				<PlaylistDetails
					name={playlist.name}
					description={playlist.description}
					tracksTotal={playlist.tracks.total}
				/>
			</PlaylistLink>
		</PlaylistListItem>
	{/each}
</PlaylistList>
