// packages/framework-compare-mitosis/vue/vue3/components/PageWrapper.vue
<template>
  <div
    class="min-h-screen bg-gradient-to-br from-slate to-darkPurple text-white min-h-screen w-full px-6 py-8"
    v-bind="$props"
  >
    <slot />
  </div>
</template>

<script lang="ts">
type PageWrapperProps = {
  children: any;
};

export default {
  name: "page-wrapper",

  props: [],
};
</script>

// apps/nextjs-app/mitosis/components/PageWrapper.tsx
import * as React from "react";

type PageWrapperProps = {
  children: any;
};

function PageWrapper(props: PageWrapperProps) {
  return (
    <div
      className="min-h-screen bg-gradient-to-br from-slate to-darkPurple text-white min-h-screen	w-full px-6 py-8"
      {...props}
    >
      {props.children}
    </div>
  );
}

export default PageWrapper;
