// packages/framework-compare-mitosis/vue/vue3/components/PlaylistDetailTitle.vue
<template>
  <h1 class="text-5xl font-normal text-center">{{ name }}</h1>
  <p class="text-2xl font-light mb-5 text-center">{{ description }}</p>
</template>

<script lang="ts">
type PlaylistDetailTitleProps = {
  name: string;
  description: string;
};

export default {
  name: "playlist-detail-title",

  props: ["name", "description"],
};
</script>

// apps/nextjs-app/mitosis/components/PlaylistDetailTitle.tsx
import * as React from "react";

type PlaylistDetailTitleProps = {
  name: string;
  description: string;
};

function PlaylistDetailTitle(props: PlaylistDetailTitleProps) {
  return (
    <>
      <h1 className="text-5xl font-normal text-center">{props.name}</h1>

      <p className="text-2xl font-light mb-5 text-center">{props.description}</p>
    </>
  );
}

export default PlaylistDetailTitle;
