// apps/svelte-kit-app/src/mitosis/components/PlaylistDetailTitle.svelte
<script context="module" lang="ts">
	type PlaylistDetailTitleProps = {
		name: string;
		description: string;
	};
</script>

<script lang="ts">
	export let name: PlaylistDetailTitleProps['name'];
	export let description: PlaylistDetailTitleProps['description'];
</script>

<h1 class="text-5xl font-normal text-center">{name}</h1>

<p class="text-2xl font-light mb-5 text-center">{description}</p>

// apps/nextjs-app/mitosis/components/PlaylistDetailTitle.tsx
import * as React from "react";

type PlaylistDetailTitleProps = {
  name: string;
  description: string;
};

function PlaylistDetailTitle(props: PlaylistDetailTitleProps) {
  return (
    <>
      <h1 className="text-5xl font-normal text-center">{props.name}</h1>

      <p className="text-2xl font-light mb-5 text-center">{props.description}</p>
    </>
  );
}

export default PlaylistDetailTitle;
