// apps/create-react-app/src/mitosis/components/TableHeader.tsx
import DownArrow from "./DownArrow";
import UpArrow from "./UpArrow";

type TableHeaderProps = {
  children: any;
  sorted: boolean;
  ascending: boolean;
};

function TableHeader(props: TableHeaderProps) {
  return (
    <div className="flex items-center gap-4 w-full">
      <div>{props.children}</div>

      {props.sorted ? (
        <>
          {props.ascending ? (
            <>
              <div>
                <UpArrow />
              </div>
            </>
          ) : (
            <div>
              <DownArrow />
            </div>
          )}
        </>
      ) : (
        <div className="w-6"> </div>
      )}
    </div>
  );
}

export default TableHeader;

// packages/framework-compare-mitosis/solid/components/TableHeader.tsx
import { Show } from "solid-js";

type TableHeaderProps = {
  children: any;
  sorted: boolean;
  ascending: boolean;
};

import DownArrow from "./DownArrow.jsx";
import UpArrow from "./UpArrow.jsx";

function TableHeader(props: TableHeaderProps) {
  return (
    <div class="flex items-center gap-4 w-full">
      <div>{props.children}</div>
      <Show fallback={<div class="w-6"></div>} when={props.sorted}>
        <Show
          fallback={
            <div>
              <DownArrow></DownArrow>
            </div>
          }
          when={props.ascending}
        >
          <div>
            <UpArrow></UpArrow>
          </div>
        </Show>
      </Show>
    </div>
  );
}

export default TableHeader;
