// apps/qwik-app/src/routes/playlist/[id]/index.tsx
import { component$, useStore, $ } from "@builder.io/qwik";
import { routeLoader$ } from "@builder.io/qwik-city";
import {
  PlaylistDetailTitle,
  TableHeader,
  TrackTable,
  TrackTableHeaderAlbumImage,
  TrackTableHeaderArtist,
  TrackTableHeaderDuration,
  TrackTableHeaderTitle,
  TrackTableRow,
} from "~/mitosis";
import type { PlaylistColumns, SortState } from "framework-compare-types";
import {
  ASCENDING,
  DESCENDING,
  NAME_COLUMN,
  ARTIST_COLUMN,
  DURATION_COLUMN,
} from "framework-compare-types";
import { millisecondDisplay, sortTracks } from "framework-compare-utils";
import { api } from "~/service/api";

export const usePlaylists = routeLoader$(async ({ cookie, params }) => {
  const playlistResponse = await api.getPlaylistDetails(
    params.id,
    cookie.get("access_token")?.value
  );
  return playlistResponse;
});

export default component$(() => {
  const playlist = usePlaylists();

  const { name, description, tracks } = playlist.value;

  const initialSort = sortTracks(
    tracks.items.map((i) => i.track),
    NAME_COLUMN,
    DESCENDING
  );

  const state = useStore<SortState>({
    tracks: initialSort.tracks,
    sortedColumn: NAME_COLUMN,
    sortDirection: ASCENDING,
  });

  const ascending = state.sortDirection === ASCENDING;

  const sort = (column: PlaylistColumns) =>
    $(() => {
      const newSort = sortTracks(
        tracks.items.map((i) => i.track),
        column,
        state.sortedColumn === column ? state.sortDirection : DESCENDING
      );
      state.tracks = newSort.tracks;
      state.sortedColumn = column;
      state.sortDirection = newSort.newDirection;
    });

  return (
    <section>
      <PlaylistDetailTitle name={name} description={description ?? ""} />

      <TrackTable>
        <thead>
          <tr>
            <TrackTableHeaderAlbumImage />
            <TrackTableHeaderTitle>
              <button onClick$={sort(NAME_COLUMN)} class="w-full">
                <TableHeader sorted={state.sortedColumn === NAME_COLUMN} ascending={ascending}>
                  TITLE
                </TableHeader>
              </button>
            </TrackTableHeaderTitle>
            <TrackTableHeaderArtist>
              <button onClick$={sort(ARTIST_COLUMN)} class="w-full">
                <TableHeader sorted={state.sortedColumn === ARTIST_COLUMN} ascending={ascending}>
                  ARTIST
                </TableHeader>
              </button>
            </TrackTableHeaderArtist>
            <TrackTableHeaderDuration>
              <button onClick$={sort(DURATION_COLUMN)} class="w-full">
                <TableHeader sorted={state.sortedColumn === DURATION_COLUMN} ascending={ascending}>
                  DURATION
                </TableHeader>
              </button>
            </TrackTableHeaderDuration>
          </tr>
        </thead>

        <tbody>
          {tracks.items.map(({ track }) => (
            <TrackTableRow
              key={track.id}
              name={track.name}
              artist={track.artists.map((a) => a.name).join(", ")}
              imageURL={track.album.images[0].url}
              duration={millisecondDisplay(track.duration_ms)}
            />
          ))}
        </tbody>
      </TrackTable>
    </section>
  );
});

// apps/nuxt-app/pages/playlist/[id].vue
<script setup>
  import { millisecondDisplay, sortTracks } from "framework-compare-utils";

  const config = useRuntimeConfig()
  const cookie = useCookie("access_token")
  const route = useRoute()

  const data = await $fetch(`${config.public.spotifyAPIEndpoint}/get-playlist-details?id=${route.params.id}`, {
    method: "GET",
    credentials: "include",
    headers: {
      cookie: `access_token=${cookie.value};`,
    }
  })

  const name = data.name
  const description = data.description

  const initialState = sortTracks(
    data.tracks?.items.map((i) => i.track) ?? [],
    NAME_COLUMN,
    DESCENDING
  );

  const playlistState = ref({
    tracks: initialState.tracks,
    sortedColumn: NAME_COLUMN,
    sortDirection: initialState.newDirection,
  })

  const sort = (column) => () => {
    const { tracks, sortDirection, sortedColumn } = playlistState.value;

    const newSort = sortTracks(
      tracks,
      column,
      sortedColumn === column ? sortDirection : DESCENDING
    );

    playlistState.value.tracks = newSort.tracks;
    playlistState.value.sortedColumn = column;
    playlistState.value.sortDirection = newSort.newDirection;
  };

</script>

<template>
  <section>
      <PlaylistDetailTitle :name="name" :description="description" />

      <TrackTable>
        <thead>
          <tr>
            <TrackTableHeaderAlbumImage />
            <TrackTableHeaderTitle>
              <button @click="sort(NAME_COLUMN)()" class="w-full">
                <TableHeader :sorted="playlistState.sortedColumn === NAME_COLUMN" :ascending="playlistState.sortDirection === ASCENDING">
                  TITLE
                </TableHeader>
              </button>
            </TrackTableHeaderTitle>
            <TrackTableHeaderArtist>
              <button @click="sort(ARTIST_COLUMN)()" class="w-full">
                <TableHeader :sorted="playlistState.sortedColumn === ARTIST_COLUMN" :ascending="playlistState.sortDirection === ASCENDING">
                  ARTIST
                </TableHeader>
              </button>
            </TrackTableHeaderArtist>
            <TrackTableHeaderDuration>
              <button @click="sort(DURATION_COLUMN)()" class="w-full">
                <TableHeader :sorted="playlistState.sortedColumn === DURATION_COLUMN" :ascending="playlistState.sortDirection === ASCENDING">
                  DURATION
                </TableHeader>
              </button>
            </TrackTableHeaderDuration>
          </tr>
        </thead>

        <tbody>
          <TrackTableRow
            v-for="track in playlistState.tracks"
            :key="track.id"
            :name="track.name"
            :artist="track.artists.map((a) => a.name).join(', ')"
            :imageURL="track.album.images[0].url"
            :duration="millisecondDisplay(track.duration_ms)"
          />
        </tbody>
      </TrackTable>
    </section>
</template>
