// apps/nextjs-app/app/layout.tsx
import { Rubik } from "next/font/google";
import Link from "next/link";
import { Header, PageWrapper, PlaylistIcon } from "../mitosis";

import "./globals.css";

const rubik = Rubik({
  weight: ["400", "500", "600", "700", "800"],
  subsets: ["latin"],
  display: "swap",
});

export const metadata = {
  title: "Next App",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={rubik.className}>
      <body>
        <PageWrapper>
          <Header>
            <Link
              href="/playlist"
              className="block border rounded-full p-2 text-white border-white"
            >
              <PlaylistIcon />
            </Link>
          </Header>
          <main>{children}</main>
        </PageWrapper>
      </body>
    </html>
  );
}

// apps/qwik-app/src/routes/layout.tsx
import { component$, Slot } from "@builder.io/qwik";
import { Header, PageWrapper, PlaylistIcon } from "~/mitosis";

export default component$(() => {
  return (
    <PageWrapper>
      <Header>
        <a href="/playlist" class="block border rounded-full p-2 text-white border-white">
          <PlaylistIcon />
        </a>
      </Header>
      <main>
        <Slot />
      </main>
    </PageWrapper>
  );
});
